[package]
name = "glasspack"
version = "0.1.0"
authors = ["Toby DiPasquale <toby@cbcg.net>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
env_logger = "0.6.1"
evmap = "4.2.2"
log = "0.4.6"
nix = "0.13.0"
